exp:
  name: cifar10
  n_train_iter: 400000
  n_rampup_iter: 5000
  eval_every: 2000
  save_every: 10000
  sigma_max: 1.0
  n_viz: 100
  use_wandb: True

defaults:
  - dataset: cifar10
  - optim: radam
  - autoencoder: cifar10_ae
  - loss: pseudohuber